name: Publish to GitBook

on:
  push:
    branches:
      - main
    paths:
      - 'gitbook/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install GitBook CLI
        run: npm install -g gitbook-cli

      - name: Install dependencies
        run: |
          cd gitbook
          gitbook install

      - name: Build book
        run: |
          cd gitbook
          gitbook build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gitbook/_book
